[package]
name = "security_monitor"
version = "0.0.2"
authors = ["Yadunandan Pillai <ytpillai@gmail.com>", "Zephyr Headley <headleyjz@vcu.edu>"]

[dependencies]
fuse = "0.3.1"
env_logger = "0.5.10"
time = "0.1"
libc = "0.2"


